### PR TITLE
Multiple intermediates

### LINKED ISSUE #16: Support including intermediate CA certificates in leaf chain
### Problem
When `step-certificates` is signed by an intermediate, and that certificate is appended to the issued CA certificate, the full chain is not included in certificates issued by `step-issuer`.

### Expected Result
Leaf certificates issued to services:

```sh
-----BEGIN CERTIFICATE-----
Leaf certificate
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
Step CA certificate
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
Intermediate CA certificate
-----END CERTIFICATE-----
```

### Actual Result
Leaf certificates issued to services:

```sh
-----BEGIN CERTIFICATE-----
Leaf certificate
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
Step CA certificate
-----END CERTIFICATE-----
```

This results in a broken chain of trust for services.

### Environment
Both `step-certificates` (`v0.17.3`) and `step-issuer` (`v0.5.1`) are installed via Helm to a `k3s` cluster.

---

At the request of @maraino via Discord, this issue is to track changing the API to include intermediate certificates.

### PR DESCRIPTION
**Pull request by maraino**
### Description

This PR uses the sign response property that supports multiple intermediates, `certChain`, instead of the old `ca` property that only has one intermediate.

Fixes #16

### CODE REVIEW

File: provisioners/step.go [hunk 1]
```diff
@@ -212,14 +202,16 @@ func decodeCSR(data []byte) (*x509.CertificateRequest, error) {
...
-func encodeX509(cert *x509.Certificate) ([]byte, error) {
-	caPem := bytes.NewBuffer([]byte{})
-	err := pem.Encode(caPem, &pem.Block{Type: "CERTIFICATE", Bytes: cert.Raw})
-	if err != nil {
-		return nil, err
+// encodeX509 will encode a certificate into PEM format.
+func encodeX509(certs ...capi.Certificate) ([]byte, error) {
+	certPem := bytes.NewBuffer([]byte{})
+	for _, cert := range certs {
+		err := pem.Encode(certPem, &pem.Block{Type: "CERTIFICATE", Bytes: cert.Raw})
```
Comment (dopey) [inline provisioners/step.go:209]: When you encode like this, does it just append the new bytes on to the end of the existing array? I would have though it overwrites it.

**Review by dopey — APPROVED** [review]
lgtm

File: provisioners/step.go (hunk 1 above)
Comment (maraino) [reply provisioners/step.go:209]: certPem is a `*bytes.Buffer`, here we're using it as an `io.Writer`, so always adding the new cert at the end.
